# Generated by Django 3.2.7 on 2021-10-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_slug', models.CharField(max_length=100)),
                ('buyer_address', models.CharField(max_length=100)),
                ('seller_address', models.CharField(max_length=100)),
                ('contract_address', models.CharField(max_length=100)),
                ('price', models.BigIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('token_id', models.CharField(max_length=256)),
                ('transaction_hash', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=20)),
            ],
        ),
    ]
